name: Docker Image app1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

   runs-on: self-hosted
   steps:
   - uses: actions/checkout@v2
   - name: Build the Docker image
     run: docker build . --file Dockerfile --tag my-image-name:hey
     
   - name: Build and Push Docker Image
     uses: mr-smithers-excellent/docker-build-push@v4
     with:
      image: firoj0786/go-app
      context: .
      push: true
      tags: user/image:latest
      registry: docker.io
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
       



Deployment

  on:
    push:
      branches:
       - main 
      runs-on: self-hosted
      steps:
      - uses: actions/checkout@v2
      - name: Deploy-stage 2
        run: docker-compose up -d
       
