name: Docker Image of go app


on:
  push:
    branches: [ main,develop ]
  pull_request:
    branches: [ main,develop ]

jobs:

  build:
      

    runs-on: self-hosted
    if: contains('refs/heads/develop',github.ref)
    steps:
    - uses: actions/checkout@v2
    - name: build_push_tag of main
     
      
      env:      
       PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
       USERNAME: ${{ secrets.DOCKER_USERNAME }}  
      
     
      run: |
            
             docker login -u $USERNAME -p $PASSWORD
             docker build -t firoj0786/mm:${{ github.sha }} -f Dockerfile .  
             docker push firoj0786/mm:${{ github.sha }}
         
             
  deploy:
 
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: deploy app
      
      run: |
      
              docker-compose  up -d
              
